### ISSUE TITLE
why the value of hash_int  is bigger than the value of target_user

### ISSUE THREAD

**Issue by windyxiao** [eveybcd/stratum-mining#2]
error:  Submit share failed, reason: [bitcoindiamond]Share is above target：

Code:

target_user = self.diff_to_target(difficulty)
        if hash_int > target_user:
            raise SubmitException("Share is above target")

Why????????

**Comment by windyxiao** [comment]
the value of diff1 is 0x00000000ffff0000000000000000000000000000000000000000000000000000 ???

**Comment by windyxiao** [comment]
extranonce2 is  '02000000',   ntime is  '5ab3150c',    nonce  is  '46bae9ed'

**Comment by zzir** [comment]
we need to finding a hash value that is less than `target_user`.

https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch10.asciidoc#proof-of-work-algorithm

**Comment by windyxiao** [comment]
hash_bin = x13bcd_hash.getPoWHash(''.join([header_bin[i * 4:i * 4 + 4][::-1] for i in range(0, 20)]))
hash_int = util.uint256_from_str(hash_bin)
block_hash_hex = "%064x" % hash_int
header_hex = binascii.hexlify(header_bin)
target_user = self.diff_to_target(difficulty)
if hash_int > target_user:
    raise SubmitException("Share is above target")

the Encryption methods is changed to x13bcd_hash,  which other places have been modified??

**Comment by zzir** [comment]
This is all the modifications. https://github.com/eveybcd/stratum-mining/commit/448b7abb306a3d8f8170c16252dbcc104d66fce2

**Comment by windyxiao** [comment]
your pool is ok?  my pool is  always print  "Share is above target"

**Comment by windyxiao** [comment]
bcd pool is not the same  of the bitcoin pool,    is it the problem of my mining machine ？

**Comment by windyxiao** [comment]
Is there complete code? thanks

**Comment by zzir** [comment]
Does your miner support the x13 algorithm?
X13_BCD algorithm for GPU mining machine.

**Comment by windyxiao** [comment]
yes, the mining machine connect to other pool is ok , but connect to my pool is print out "Share is above target"

**Comment by windyxiao** [comment]
This is  my mining machine software :   http://uupool.cn/course/bcd

**Comment by windyxiao** [comment]
Are you sure this project code is correct ? Is it running online?

**Comment by zzir** [comment]
code: https://github.com/eveybcd/stratum-mining/blob/master/lib/template_registry.py#L228
```
        target_user = self.diff_to_target(difficulty)
        if hash_int > target_user:
            raise SubmitException("Share is above target")

# change into ↓

        if hash_int > target_user:
            log.debug('hash_int %s, target_user %s, difficulty %s' % (hash_int, target_user, difficulty))
            raise SubmitException("Share is above target")
``` 
look at the log output.

**Comment by zzir** [comment]
Our mining software: https://github.com/eveybcd/gpu-miner

**Comment by windyxiao** [comment]
thanks，can your mining software  run on windows?

**Comment by windyxiao** [comment]
ok，thank you very much, I solved the problem.
